platform: linux

image_resource:
  type: docker-image
  source:
    repository: sonarqube
    tag: latest

inputs:
  - name: source-code

run:
  path: "source-code/gradlew"
  args: ["-f", "source-code/build.gradle", "assemble", "sonar:sonar"]

params:
  MAVEN_BASEDIR: source-code
